// <auto-generated />
namespace SolbergBakery2531.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addmodelcate3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmodelcate3));
        
        string IMigrationMetadata.Id
        {
            get { return "202512192013311_addmodelcate3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
